---
title: "HW02 ?大英語?課課?數變??"
author: "B04202016 ????? ?????"
date: "2017?4???24?"
output: html_document
---

```{r setup, include=FALSE}
library("dplyr")
library("plotly")
library("RColorBrewer")
require(stats)
knitr::opts_chunk$set(echo = TRUE)
```

## ?大英語?課????

> ??們???究??主題是??大???學???想??由不??數????繪?他們在?大??活?其中???????就??大?設以英語??課??課程數?由?來台大???學??????趨?，??兩?具???聯，?此?????數?????測??語?課??課程數也?????趨???



## 96~104學年度總?/??學??語?課????


```{r eng_class, echo=TRUE}
raw_data<- read.csv("eng_class.csv", sep= ",", header= TRUE)

lastsemId = length(raw_data$semester)
firstsem = raw_data$semester[1]
lastsem = raw_data$semester[lastsemId]
n = 18
allType = names(raw_data)
rownames(raw_data) <- 1:nrow(raw_data)
typeId = c(2:13)
newTable = data.frame()
for( nid in c(1:n) )
{
  semester = as.matrix(rep(raw_data$semester[nid], length(raw_data[nid,typeId])))
  class_num = as.matrix(as.numeric(raw_data[nid,typeId]))
  type = as.matrix(as.character(allType[typeId]))
  temp = cbind(semester, class_num, type)
  newTable = rbind(newTable, temp)
}
names(newTable) = c('semester', 'class_num', 'pos')
newTable = newTable[with(newTable, order(pos)),]
rownames(newTable) <- 1:nrow(newTable)

colourCount = length(unique(mtcars$hp))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

p <- plot_ly(data = newTable, x = ~semester, 
             y = ~class_num, color = ~pos, colors= getPalette(colourCount)) %>%
  add_lines( yaxis = list(range = c(0,10)))
p

```

> y軸為?語?課??課程?x軸為學?? (ex?1041->104學年度第1學??)

> ??張??表來???可以?出?學??語?課??課程總????顯增??趨? (約??400增?到?550)，大?上是符?????測???學???英語課程數??卻?沒??顯????趨???

##96~104學年度?學??語?課????
```{r echo= TRUE}
newTable<- newTable[0:198, ]
rownames(newTable) <- 1:nrow(newTable)

colourCount = length(unique(mtcars$hp))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

p <- plot_ly(data = newTable, x = ~semester, 
             y = ~class_num, color = ~pos, colors= getPalette(colourCount)) %>%
  add_lines( yaxis = list(range = c(0,10)))
p
```

#

> ???學??語課程總?後?放大檢視?學????差??其中?學???英語課程數???顯多於?他學?，??大??可??是外?系??導致??????為比起?他學?，?學???英語課程數???而????趨?，??系中英語?課???象主??是????學??????學???無??聯；而其他學???然上???度並?大，?在?幾年中，英語?課??課程數???增??

> ??然並?能以此就斷定以?語?課??課程數????學??人???????? (???學??人?增?而???設?多英語課程???是?語課程數????吸引???學???)，?這次?????是?以說??台大?設??英語課程?確???????能???多?數??支??? (例???學??修習英語課程??英語課程?????是??種課程中??績?????)，那?份????許就能夠?為一?????略窺??學??在?大?學習?況?
